#ffffff| bg           |
#eaeaea| bg_alt       |
#acacac| bg_highlight |
#16181a| fg           |
#7b8496| grey         |
#5ea1ff| blue         |
#5eff6c| green        |
#5ef1ff| cyan         |
#ff6e5e| red          |
#f1ff5e| yellow       |
#ff5ef1| magenta      |
#ff5ea0| pink         |
#ffbd5e| orange       |
#bd5eff| purple       |

file_panel_border = "#acacac"
sidebar_border = "#eaeaea"
footer_border = "#acacac"

file_panel_border_active = "#ff5ea0"
sidebar_border_active = "#ffbd5e"
footer_border_active = "#ff5ea0"
modal_border_active = "#ff5ea0"

full_screen_bg = "#ffffff"
file_panel_bg = "#ffffff"
sidebar_bg = "#ffffff"
footer_bg = "#ffffff"
modal_bg = "#ffffff"

full_screen_fg = "#16181a"
file_panel_fg = "#16181a"
sidebar_fg = "#16181a"
footer_fg = "#16181a"
modal_fg = "#16181a"

cursor = "#5eff6c"
correct = "#5eff6c"
error = "#ff6e5e"
hint = "#5ea1ff"
cancel = "#ffbd5e"
# Gradient color can only have two color!
gradient_color = ["#5ea1ff", "#bd5eff"]

file_panel_top_directory_icon = "#5eff6c"
file_panel_top_path = "#5eff6c"
file_panel_item_selected_fg = "#ffbd5e"
file_panel_item_selected_bg = ""

sidebar_title = "#ffbd5e"
sidebar_item_selected_fg = "#5eff6c"
sidebar_item_selected_bg = ""
sidebar_divider = "#eaeaea"

modal_cancel_fg = "#acacac"
modal_cancel_bg = "#ff6e5e"

modal_confirm_fg = "#3c4048"
modal_confirm_bg = "#5eff6c"

help_menu_hotkey = "#5eff6c"
help_menu_title = "#ffbd5e"
